<?php
/**
 * ADMIN SCHEMA — describes every editable setting per board.
 * admin.php renders forms from this; boards never read it.
 *
 * Field types:
 *   text | password | number | bool | select (options) | textarea
 *   rows   — repeatable row editor. 'columns' define the cells.
 *            'keyed' => true  → saved as a map, first column is the key
 *            'scalar' => true → keyed map of key => single value (2 columns)
 *            otherwise        → saved as a list of objects
 *   json   — raw JSON textarea with validation (for complex structures)
 */

require_once __DIR__ . '/config.php';

/** One pages-editor field per configured screen. */
function rotation_page_fields(): array
{
    $screens = cfg('rotation.SCREENS', ['main' => 'Main Display']);
    if (!is_array($screens) || $screens === []) $screens = ['main' => 'Main Display'];
    if (!isset($screens['main'])) $screens = ['main' => 'Main Display'] + $screens;
    $cols = [['key' => 'url', 'label' => 'URL', 'wide' => true, 'placeholder' => 'rss.php?feed=ars'],
             ['key' => 'dwell', 'label' => 'Dwell (s)', 'cast' => 'int'],
             ['key' => 'from', 'label' => 'From hr', 'cast' => 'int'],
             ['key' => 'to', 'label' => 'To hr', 'cast' => 'int'],
             ['key' => 'weight', 'label' => 'Weight', 'cast' => 'int',
              'help' => 'Per-page show frequency when Weighted is on (1–20, default 1)'],
             ['key' => 'off', 'label' => 'Skip', 'type' => 'check']];
    $out = [];
    foreach ($screens as $key => $scr) {
        $name = is_array($scr) ? ($scr['name'] ?? $key) : $scr;   // tolerate the older key=>name shape
        $out[] = ['key' => 'PAGES_' . $key, 'label' => 'Pages — ' . $name . ' (?screen=' . $key . ')',
                  'type' => 'rows', 'columns' => $cols,
                  'help' => $key === 'main'
                      ? 'Edited on this page as a drag-and-drop playlist. Relative board URLs in display order.'
                      : 'Leave empty to mirror the main screen.'];
    }
    return $out;
}

function admin_schema(): array
{
    $tz  = ['key' => 'TIMEZONE', 'label' => 'Timezone', 'type' => 'text', 'help' => 'PHP timezone, e.g. America/Detroit'];
    $ttl = fn($h = '') => ['key' => 'CACHE_TTL', 'label' => 'Cache TTL (seconds)', 'type' => 'number', 'help' => $h ?: 'How long API responses are cached'];

    return [
        'security' => ['title' => 'Security', 'fields' => [
            ['key' => 'ALLOW_PRIVATE_FETCH', 'label' => 'Allow private URL fetches', 'type' => 'bool', 'default' => false,
             'help' => 'Lets RSS/ICS boards fetch http(s) URLs on private LAN IPs. Leave off on public servers.'],
            ['key' => 'ADMIN_IDLE_MINUTES', 'label' => 'Admin idle timeout (minutes)', 'type' => 'number', 'default' => 480,
             'help' => 'Auto-logout after inactivity (minimum 15). Default 480 = 8 hours.'],
            ['key' => 'SSO_ENABLED', 'label' => 'Enable SSO login', 'type' => 'bool', 'default' => false,
             'help' => 'OpenID Connect sign-in for admin. Local login can remain available below.'],
            ['key' => 'SSO_PROVIDER', 'label' => 'SSO provider', 'type' => 'select',
             'options' => ['generic', 'entra', 'authentik'], 'default' => 'generic',
             'help' => 'Preset for setup hints — both Entra and Authentik use standard OIDC under the hood.'],
            ['key' => 'SSO_ISSUER_URL', 'label' => 'OIDC issuer URL', 'type' => 'text',
             'help' => 'Entra: https://login.microsoftonline.com/<tenant-id>/v2.0 · Authentik: provider issuer URL (match trailing slash exactly).'],
            ['key' => 'OIDC_CLIENT_ID', 'label' => 'OIDC client ID', 'type' => 'text'],
            ['key' => 'OIDC_CLIENT_SECRET', 'label' => 'OIDC client secret', 'type' => 'password'],
            ['key' => 'OIDC_SCOPES', 'label' => 'OIDC scopes', 'type' => 'text', 'default' => 'openid profile email',
             'help' => 'Space-separated. Default works for Entra and Authentik.'],
            ['key' => 'SSO_USERNAME_CLAIM', 'label' => 'Username claim', 'type' => 'text', 'default' => 'preferred_username',
             'help' => 'JWT claim matched to admin username. Falls back to email / upn (Entra).'],
            ['key' => 'SSO_AUTO_LINK_EMAIL', 'label' => 'Auto-link by email', 'type' => 'bool', 'default' => true,
             'help' => 'On first SSO sign-in, match existing users when the email local-part equals their username.'],
            ['key' => 'SSO_ALLOW_LOCAL_FALLBACK', 'label' => 'Allow local password login', 'type' => 'bool', 'default' => true,
             'help' => 'When SSO is enabled, still show username/password on the login page.'],
            ['key' => 'SSO_JIT_ENABLED', 'label' => 'SSO just-in-time provisioning', 'type' => 'bool', 'default' => false,
             'help' => 'Create operator accounts automatically on first SSO sign-in (no pre-registration). Never creates super admins.'],
            ['key' => 'SSO_JIT_ALLOWED_DOMAINS', 'label' => 'JIT allowed email domains', 'type' => 'text',
             'help' => 'Comma-separated domains (e.g. contoso.com). Blank = any domain. Requires email claim in token.'],
            ['key' => 'SSO_JIT_REQUIRE_GROUPS', 'label' => 'JIT required groups/roles', 'type' => 'text',
             'help' => 'Comma-separated; user must have any listed group or app role in the token (Entra: add groups/roles to token). Blank = no group filter.'],
            ['key' => 'AUDIT_ENABLED', 'label' => 'Enable audit log', 'type' => 'bool', 'default' => true,
             'help' => 'Record admin logins, saves, and user changes. Super admins view under Audit.'],
            ['key' => 'AUDIT_MAX_ENTRIES', 'label' => 'Audit log max entries', 'type' => 'number', 'default' => 2000,
             'help' => 'Oldest entries are dropped when the log exceeds this size (100–20000).'],
            ['key' => 'OPERATOR_MULTI_SCREEN', 'label' => 'Operators may manage multiple displays', 'type' => 'bool', 'default' => true,
             'help' => 'When on, assign more than one rotation display per operator under Users. When off, each operator gets exactly one display.'],
        ]],
        'rotation' => ['title' => 'Rotation', 'file' => 'board.php', 'fields' => array_merge([
            ['key' => 'SCREENS', 'label' => 'Screens', 'type' => 'rows', 'keyed' => true,
             'columns' => [['key' => '_key', 'label' => 'Key', 'help' => 'used in ?screen='],
                           ['key' => 'name', 'label' => 'Display name'],
                           ['key' => 'show_ticker', 'label' => 'Weather ticker', 'type' => 'check'],
                           ['key' => 'show_clock', 'label' => 'Clock', 'type' => 'check'],
                           ['key' => 'show_debug', 'label' => 'Debug', 'type' => 'check'],
                           ['key' => 'keyboard_nav', 'label' => 'Keys', 'type' => 'check'],
                           ['key' => 'fade_ms', 'label' => 'Crossfade (ms)'],
                           ['key' => 'settle_ms', 'label' => 'Settle (ms)'],
                           ['key' => 'hang_ms', 'label' => 'Hang (ms)'],
                           ['key' => 'weighted', 'label' => 'Weighted', 'type' => 'check',
                            'help' => 'Random next page by entry weight; overrides Shuffle'],
                           ['key' => 'shuffle', 'label' => 'Shuffle', 'type' => 'check'],
                           ['key' => 'schedule_enabled', 'label' => 'Blank', 'type' => 'check'],
                           ['key' => 'cec_off', 'label' => 'Off hr'],
                           ['key' => 'cec_on', 'label' => 'On hr'],
                           ['key' => 'weekdays', 'label' => 'Days', 'type' => 'weekdays'],
                           ['key' => 'cec_enabled', 'label' => 'CEC', 'type' => 'check']],
             'help' => 'One row per physical display. Each kiosk points at board.php?screen=<key> '
                     . '(plain board.php = the "main" screen). Save after adding a screen and its '
                     . 'page list appears below. Keys enables ←/→ manual playlist control on that display. '
                     . 'A screen with no pages of its own falls back to main. '
                     . 'Blank shows a dark screen during Off→On hours (rotation timezone). Pick weekdays to limit '
                     . 'when the display is active (e.g. Mon–Fri only — weekends stay blank all day). '
                     . 'CEC is optional HDMI standby on Pi kiosks.'],
        ], rotation_page_fields(), [
            $tz,
            ['key' => 'FADE_MS', 'label' => 'Crossfade (ms)', 'type' => 'number'],
            ['key' => 'SETTLE_MS', 'label' => 'Settle after load (ms)', 'type' => 'number',
             'help' => 'Lets fonts/maps finish before reveal'],
            ['key' => 'HANG_MS', 'label' => 'Hung-page timeout (ms)', 'type' => 'number'],
        ])],
        'index' => ['title' => 'Weather', 'file' => 'index.php', 'fields' => [
            ['key' => 'OWM_API_KEY', 'label' => 'OpenWeatherMap API key', 'type' => 'password'],
            ['key' => 'LOCATION', 'label' => 'Location name', 'type' => 'text'],
            ['key' => 'LAT', 'label' => 'Latitude', 'type' => 'number', 'step' => 'any',
             'help' => 'Default for weather boards and the NWS alert ticker; override per display under Rotation → Kiosk settings'],
            ['key' => 'LON', 'label' => 'Longitude', 'type' => 'number', 'step' => 'any',
             'help' => 'Default for weather boards and the NWS alert ticker; override per display under Rotation → Kiosk settings'],
            ['key' => 'UNITS', 'label' => 'Units', 'type' => 'select', 'options' => ['imperial', 'metric']],
            ['key' => 'RADAR_URL', 'label' => 'Fallback radar GIF URL', 'type' => 'text',
             'help' => 'NWS RIDGE loop used if RainViewer fails'],
            $tz, $ttl(),
        ]],
        'lake' => ['title' => 'Lake Michigan', 'file' => 'lake.php', 'fields' => [
            ['key' => 'NDBC_STATION', 'label' => 'NDBC station ID', 'type' => 'text', 'help' => 'e.g. 45029 (Holland nearshore — wave height); 45161 Muskegon often lacks WVHT'],
            ['key' => 'STATION_NAME', 'label' => 'Station display name', 'type' => 'text'],
            ['key' => 'BEACH_NAME', 'label' => 'Beach name', 'type' => 'text'],
            ['key' => 'LAT', 'label' => 'Latitude', 'type' => 'number', 'step' => 'any'],
            ['key' => 'LON', 'label' => 'Longitude', 'type' => 'number', 'step' => 'any'],
            ['key' => 'NWS_UA', 'label' => 'NWS User-Agent', 'type' => 'text', 'help' => 'Include a contact email — NWS asks for it'],
            $tz, $ttl(),
        ]],
        'webcam' => ['title' => 'Webcam', 'file' => 'webcam.php', 'fields' => [
            ['key' => 'TITLE', 'label' => 'Overlay title', 'type' => 'text',
             'help' => 'Shown above the camera name when overlay is on'],
            ['key' => 'CAMS', 'label' => 'Cameras', 'type' => 'rows', 'keyed' => true,
             'help' => 'Built-in feeds are always available; rows here override names/URLs or add your own. Each camera is its own rotation slot (webcam.php?cam=KEY), like Zabbix pages or RSS feeds.',
             'columns' => [
                 ['key' => '_key', 'label' => 'Key', 'help' => 'used in ?cam='],
                 ['key' => 'name', 'label' => 'Display name'],
                 ['key' => 'url', 'label' => 'URL', 'wide' => true,
                  'help' => 'Iframe embed, WetMet stream frame.php, direct .jpg/.png, or still widget URL'],
                 ['key' => 'kind', 'label' => 'Type', 'type' => 'select',
                  'options' => ['' => 'Auto', 'iframe' => 'Iframe embed', 'stream' => 'Live stream (HLS)', 'image' => 'Direct image URL', 'widget' => 'Still-image widget'],
                  'help' => 'Auto detects iframe, WetMet live stream, direct image, or still widget.'],
                 ['key' => 'attribution', 'label' => 'Attribution', 'wide' => true],
                 ['key' => 'off', 'label' => 'Off', 'type' => 'bool',
                  'help' => 'Hide from quick-add and disable built-in override'],
             ]],
            ['key' => 'ATTRIBUTION', 'label' => 'Default attribution', 'type' => 'text',
             'help' => 'Fallback credit bottom-right when a camera has no attribution; blank hides if camera also blank'],
            ['key' => 'SHOW_OVERLAY', 'label' => 'Show title + clock overlay', 'type' => 'bool', 'default' => true],
            ['key' => 'IMAGE_REFRESH_SEC', 'label' => 'Still-image refresh (seconds)', 'type' => 'number',
             'help' => 'Widget/direct still cameras — default 15'],
            ['key' => 'STREAM_REFRESH_SEC', 'label' => 'Live stream token refresh (seconds)', 'type' => 'number',
             'help' => 'HLS stream cameras — re-fetch signed playlist URL before expiry — default 1500 (25 min)'],
            ['key' => 'RELOAD_SEC', 'label' => 'Iframe reload (seconds)', 'type' => 'number',
             'help' => 'Backstop for iframe streams in long kiosk sessions — 0 disables (default 3600)'],
            $tz,
        ]],
        'bridgecam' => ['title' => 'Mackinac Bridge Cam', 'file' => 'bridgecam.php', 'fields' => [
            ['key' => 'TITLE', 'label' => 'Overlay title', 'type' => 'text'],
            ['key' => 'CAMERA', 'label' => 'Camera', 'type' => 'select',
             'options' => ['4' => 'Mackinaw City · north (default)', '1' => 'Administration building · south',
                           '2' => 'St. Ignace dock · south', '3' => 'Bridge View Park · south',
                           'all' => 'Rotate all four cameras'],
             'default' => '4'],
            ['key' => 'ATTRIBUTION', 'label' => 'Attribution line', 'type' => 'text',
             'help' => 'Small credit bottom-right; leave blank to hide'],
            ['key' => 'SHOW_OVERLAY', 'label' => 'Show title + clock overlay', 'type' => 'bool', 'default' => true],
            ['key' => 'REFRESH_SEC', 'label' => 'Image refresh (seconds)', 'type' => 'number',
             'help' => 'Source updates about every 60s — default 60'],
            ['key' => 'ROTATE_SEC', 'label' => 'Camera rotation (seconds)', 'type' => 'number',
             'help' => 'When showing all cameras — default 45'],
            $tz,
        ]],
        'photo' => ['title' => 'Photo Conditions', 'file' => 'photo.php', 'fields' => [
            ['key' => 'OWM_API_KEY', 'label' => 'OpenWeatherMap API key', 'type' => 'password'],
            ['key' => 'PLACE', 'label' => 'Place name', 'type' => 'text'],
            ['key' => 'LAT', 'label' => 'Latitude', 'type' => 'number', 'step' => 'any'],
            ['key' => 'LON', 'label' => 'Longitude', 'type' => 'number', 'step' => 'any'],
            $tz, $ttl(),
        ]],
        'air' => ['title' => 'Air & Pollen', 'file' => 'air.php', 'fields' => [
            ['key' => 'TITLE', 'label' => 'Board title', 'type' => 'text'],
            ['key' => 'PLACE', 'label' => 'Place name', 'type' => 'text'],
            ['key' => 'LAT', 'label' => 'Latitude', 'type' => 'number', 'step' => 'any'],
            ['key' => 'LON', 'label' => 'Longitude', 'type' => 'number', 'step' => 'any'],
            ['key' => 'GOOGLE_POLLEN_API_KEY', 'label' => 'Google Pollen API key', 'type' => 'password',
             'help' => 'Pollen only (not AQI). Enable Pollen API in Google Cloud; free tier is 5,000 calls/month.'],
            ['key' => 'AIRNOW_API_KEY', 'label' => 'EPA AirNow API key', 'type' => 'password',
             'help' => 'AQI from EPA ground monitors (not airnow.gov). Register at docs.airnowapi.org/account/request/, activate via email, log in, open Web Services — API key is in the upper-right corner. Paste here and Save.'],
            ['key' => 'RELOAD_SEC', 'label' => 'Page reload (seconds)', 'type' => 'number',
             'help' => 'Direct view only — rotation iframe reloads with the shell'],
            ['key' => 'NWS_CACHE_TTL', 'label' => 'NWS alert cache (seconds)', 'type' => 'number',
             'help' => 'NWS has no API key or quota — default 300s (5 min) so alerts refresh sooner than AQI/pollen'],
            $tz, $ttl('AirNow, Google Pollen, Open-Meteo — default 3600s (1 h)'),
        ]],
        'uv' => ['title' => 'UV Index', 'file' => 'uv.php', 'fields' => [
            ['key' => 'TITLE', 'label' => 'Board title', 'type' => 'text'],
            ['key' => 'PLACE', 'label' => 'Place name', 'type' => 'text'],
            ['key' => 'LAT', 'label' => 'Latitude', 'type' => 'number', 'step' => 'any'],
            ['key' => 'LON', 'label' => 'Longitude', 'type' => 'number', 'step' => 'any'],
            ['key' => 'RELOAD_SEC', 'label' => 'Page reload (seconds)', 'type' => 'number',
             'help' => 'Direct view only — rotation iframe reloads with the shell'],
            $tz, $ttl('Open-Meteo forecast responses — default 900s (15 min)'),
        ]],
        'wotd' => ['title' => 'Word of the Day', 'file' => 'wotd.php', 'fields' => [
            ['key' => 'TITLE', 'label' => 'Board title', 'type' => 'text'],
            ['key' => 'SUBTITLE', 'label' => 'Subtitle', 'type' => 'text'],
            ['key' => 'RELOAD_SEC', 'label' => 'Page reload (seconds)', 'type' => 'number',
             'help' => 'Direct view only — rotation iframe reloads with the shell'],
            $tz, $ttl('Wordsmith + dictionary responses — default 86400s (24 h)'),
        ]],
        'history' => ['title' => 'This Day in History', 'file' => 'history.php', 'fields' => [
            ['key' => 'TITLE', 'label' => 'Board title', 'type' => 'text'],
            ['key' => 'SUBTITLE', 'label' => 'Subtitle', 'type' => 'text'],
            ['key' => 'MAX_ITEMS', 'label' => 'Highlight count', 'type' => 'number',
             'help' => 'Featured + list items from Wikipedia (4–12, default 8)'],
            ['key' => 'RELOAD_SEC', 'label' => 'Page reload (seconds)', 'type' => 'number',
             'help' => 'Direct view only — rotation iframe reloads with the shell'],
            $tz, $ttl('Wikipedia on-this-day — default 86400s (24 h)'),
        ]],
        'joke' => ['title' => 'Dad Jokes', 'file' => 'joke.php', 'fields' => [
            ['key' => 'TITLE', 'label' => 'Board title', 'type' => 'text'],
            ['key' => 'SUBTITLE', 'label' => 'Subtitle', 'type' => 'text'],
            ['key' => 'USER_AGENT', 'label' => 'API User-Agent', 'type' => 'text',
             'help' => 'icanhazdadjoke.com asks for a descriptive User-Agent with contact info'],
            ['key' => 'RELOAD_SEC', 'label' => 'Page reload (seconds)', 'type' => 'number',
             'help' => '0 in rotation (default) — shell reloads each visit; set 60+ for direct/kiosk view'],
            $tz, $ttl('Random joke — default 90s; lower = new joke more often in rotation'),
        ]],
        'announce' => ['title' => 'Announcements', 'file' => 'announce.php', 'fields' => [
            ['key' => 'BOARD_TITLE', 'label' => 'Default title', 'type' => 'text', 'default' => 'Announcement'],
            ['key' => 'BOARD_SUB', 'label' => 'Default subtitle', 'type' => 'text'],
            ['key' => 'ITEMS', 'label' => 'Announcements', 'type' => 'rows', 'keyed' => true,
             'columns' => [
                 ['key' => '_key', 'label' => 'Key', 'help' => 'used in announce.php?d='],
                 ['key' => 'title', 'label' => 'Title'],
                 ['key' => 'body', 'label' => 'Message', 'wide' => true],
                 ['key' => 'mode', 'label' => 'Mode', 'type' => 'select',
                  'options' => ['announcement', 'countdown'], 'help' => 'Countdown shows time until countdown_until'],
                 ['key' => 'countdown_until', 'label' => 'Countdown until', 'help' => 'YYYY-MM-DD or YYYY-MM-DD HH:MM — countdown mode'],
                 ['key' => 'start_at', 'label' => 'Show from', 'help' => 'Optional — blank = immediately'],
                 ['key' => 'end_at', 'label' => 'Hide after', 'help' => 'Optional expiry'],
                 ['key' => 'strip_only', 'label' => 'Strip only', 'type' => 'bool',
                  'help' => 'Hero strip only — omitted from rotation quick-add'],
             ],
             'help' => 'Each row is its own rotation page: announce.php?d=<key>'],
            $tz,
        ]],
        'xkcd' => ['title' => 'XKCD Comic', 'file' => 'xkcd.php', 'fields' => [
            ['key' => 'TITLE', 'label' => 'Board title', 'type' => 'text'],
            ['key' => 'SUBTITLE', 'label' => 'Subtitle', 'type' => 'text'],
            ['key' => 'SHOW_ALT', 'label' => 'Show hover text', 'type' => 'bool', 'default' => true,
             'help' => 'The alt line under the comic — often the best part'],
            ['key' => 'RELOAD_SEC', 'label' => 'Page reload (seconds)', 'type' => 'number',
             'help' => 'Direct view only — rotation iframe reloads with the shell'],
            $tz, $ttl('Latest comic from xkcd.com — default 86400s (24 h)'),
        ]],
        'sports' => ['title' => 'Sports', 'file' => 'sports.php', 'fields' => [
            ['key' => 'TITLE', 'label' => 'Board title', 'type' => 'text'],
            ['key' => 'SUBTITLE', 'label' => 'Subtitle', 'type' => 'text',
             'help' => 'Shown beside the title — default lists all four teams'],
            ['key' => 'RELOAD_SEC', 'label' => 'Live-game reload (seconds)', 'type' => 'number',
             'help' => 'Direct view only — auto-refresh while a game is live (rotation reloads with the shell)'],
            $tz, $ttl('ESPN responses — default 300s; live games refresh sooner'),
        ]],
        'signaltrace' => ['title' => 'SignalTrace', 'file' => 'signaltrace.php', 'fields' => [
            ['key' => 'ST_BASE_URL', 'label' => 'SignalTrace base URL', 'type' => 'text'],
            ['key' => 'ST_EXPORT_TOKEN', 'label' => 'Export API token', 'type' => 'password',
             'help' => 'EXPORT_API_TOKEN from includes/config.local.php — used server-side only'],
            ['key' => 'WINDOW_HOURS', 'label' => 'Window (hours)', 'type' => 'number'],
            ['key' => 'IGNORE_IPS', 'label' => 'Ignore IPs in feed', 'type' => 'text',
             'help' => 'Comma-separated — hide your signage/homelab monitor IP from Recent Activity (e.g. 192.168.1.50)'],
            $tz, $ttl(),
        ]],
        'outages' => ['title' => 'Cloud Outages', 'file' => 'outages.php', 'fields' => [
            ['key' => 'TITLE', 'label' => 'Board title', 'type' => 'text'],
            ['key' => 'SUBTITLE', 'label' => 'Subtitle', 'type' => 'text'],
            ['key' => 'ENABLE_AWS', 'label' => 'Show AWS', 'type' => 'bool', 'default' => true],
            ['key' => 'ENABLE_AZURE', 'label' => 'Show Azure', 'type' => 'bool', 'default' => true],
            ['key' => 'ENABLE_GITHUB', 'label' => 'Show GitHub', 'type' => 'bool', 'default' => true],
            ['key' => 'ENABLE_CLOUDFLARE', 'label' => 'Show Cloudflare', 'type' => 'bool', 'default' => true],
            ['key' => 'ENABLE_O365', 'label' => 'Show Microsoft 365', 'type' => 'bool', 'default' => true],
            ['key' => 'ENABLE_GOOGLE', 'label' => 'Show Google Workspace', 'type' => 'bool', 'default' => true],
            ['key' => 'US_ONLY', 'label' => 'US incidents only', 'type' => 'bool', 'default' => true,
             'help' => 'Filter AWS, Azure, Cloudflare POPs, and Google Workspace to US-affected incidents. GitHub has no regional feed — shows global status.'],
            ['key' => 'MAX_ISSUES', 'label' => 'Issues per provider', 'type' => 'number',
             'help' => 'How many incidents to list on each card (1–5, default 3)'],
            ['key' => 'MS_GRAPH_TENANT_ID', 'label' => 'M365 tenant ID (optional)', 'type' => 'text',
             'help' => 'Optional — unlocks tenant-specific Exchange/Teams/SharePoint health via Graph (ServiceHealth.Read.All). Without this, the board uses the public backup status feed only.'],
            ['key' => 'MS_GRAPH_CLIENT_ID', 'label' => 'M365 client ID', 'type' => 'text'],
            ['key' => 'MS_GRAPH_CLIENT_SECRET', 'label' => 'M365 client secret', 'type' => 'password'],
            ['key' => 'RELOAD_SEC', 'label' => 'Page reload (seconds)', 'type' => 'number',
             'help' => 'Direct view only — rotation iframe reloads with the shell'],
            $tz, $ttl('Public status feeds — default 120s'),
        ]],
        'hibp' => ['title' => 'Data Breaches', 'file' => 'hibp.php', 'fields' => [
            ['key' => 'TITLE', 'label' => 'Board title', 'type' => 'text'],
            ['key' => 'SUBTITLE', 'label' => 'Subtitle', 'type' => 'text'],
            ['key' => 'MAX_ITEMS', 'label' => 'Breach count', 'type' => 'number',
             'help' => 'Featured + list items sorted by date added (4–12, default 8)'],
            ['key' => 'USER_AGENT', 'label' => 'User-Agent', 'type' => 'text',
             'help' => 'HIBP requires a descriptive User-Agent — no API key needed for the breaches feed'],
            ['key' => 'RELOAD_SEC', 'label' => 'Page reload (seconds)', 'type' => 'number',
             'help' => 'Direct view only — rotation iframe reloads with the shell'],
            $tz, $ttl('HIBP breach list — default 3600s (1 h)'),
        ]],
        'cve' => ['title' => 'New CVEs', 'file' => 'cve.php', 'fields' => [
            ['key' => 'TITLE', 'label' => 'Board title', 'type' => 'text'],
            ['key' => 'SUBTITLE', 'label' => 'Subtitle', 'type' => 'text'],
            ['key' => 'MAX_ITEMS', 'label' => 'CVE count', 'type' => 'number',
             'help' => 'Featured + list items, newest first (4–12, default 8)'],
            ['key' => 'LOOKBACK_DAYS', 'label' => 'Lookback (days)', 'type' => 'number',
             'help' => 'Query NVD for CVEs published in the last N days (1–30, default 7)'],
            ['key' => 'NVD_API_KEY', 'label' => 'NVD API key', 'type' => 'password',
             'help' => 'Optional — raises rate limits; request at nvd.nist.gov/developers/request-an-api-key'],
            ['key' => 'USER_AGENT', 'label' => 'User-Agent', 'type' => 'text',
             'help' => 'Sent on NVD requests — include contact info'],
            ['key' => 'RELOAD_SEC', 'label' => 'Page reload (seconds)', 'type' => 'number',
             'help' => 'Direct view only — rotation iframe reloads with the shell'],
            $tz, $ttl('NVD CVE responses — default 3600s (1 h)'),
        ]],
        'ransomware' => ['title' => 'Ransomware Tracker', 'file' => 'ransomware.php', 'fields' => [
            ['key' => 'TITLE', 'label' => 'Board title', 'type' => 'text', 'default' => 'Ransomware tracker'],
            ['key' => 'SUBTITLE', 'label' => 'Subtitle', 'type' => 'text', 'default' => 'Ransomware.live'],
            ['key' => 'MAX_ITEMS', 'label' => 'Victim count', 'type' => 'number',
             'help' => 'Hero + list rows from recent extortion-site claims (4–12, default 8)'],
            ['key' => 'LOOKBACK_DAYS', 'label' => 'Lookback (days)', 'type' => 'number',
             'help' => 'Only show claims discovered in the last N days (1–30, default 7)'],
            ['key' => 'HIGHLIGHT_COUNTRY', 'label' => 'Highlight country', 'type' => 'text', 'default' => 'US',
             'help' => 'ISO country code — pins and accents matching rows (blank disables)'],
            ['key' => 'WATCH_SECTORS', 'label' => 'Watch sectors', 'type' => 'text', 'wide' => true,
             'help' => 'Optional comma-separated activity/sector filters (e.g. Healthcare, Education). Blank = all sectors.'],
            ['key' => 'WATCH_GROUPS', 'label' => 'Watch groups', 'type' => 'text', 'wide' => true,
             'help' => 'Optional comma-separated ransomware group slugs (e.g. akira, qilin). Blank = all groups.'],
            ['key' => 'SHOW_INFOSTEALER', 'label' => 'Show infostealer user counts', 'type' => 'bool', 'default' => true],
            ['key' => 'USER_AGENT', 'label' => 'User-Agent', 'type' => 'text',
             'help' => 'Sent on Ransomware.live requests — include contact info'],
            ['key' => 'RELOAD_SEC', 'label' => 'Page reload (seconds)', 'type' => 'number',
             'help' => 'Direct view only — rotation iframe reloads with the shell'],
            $tz, $ttl('Ransomware.live recent victims — default 1800s (respect 1 req/min API limit)'),
        ]],
        'phish' => ['title' => 'Phishing & Brand Threats', 'file' => 'phish.php', 'fields' => [
            ['key' => 'TITLE', 'label' => 'Board title', 'type' => 'text', 'default' => 'Phishing & brand threats'],
            ['key' => 'SUBTITLE', 'label' => 'Subtitle', 'type' => 'text', 'default' => 'abuse.ch · crt.sh'],
            ['key' => 'URLHAUS_AUTH_KEY', 'label' => 'URLhaus Auth-Key', 'type' => 'password',
             'help' => 'Free at auth.abuse.ch — required for urlhaus-api.abuse.ch recent URLs feed'],
            ['key' => 'TAGS_INCLUDE', 'label' => 'Tags include', 'type' => 'text', 'wide' => true,
             'help' => 'Optional comma-separated tag/threat filters (e.g. emotet, qakbot, cobalt). Blank = all recent URLs.'],
            ['key' => 'ONLINE_ONLY', 'label' => 'Online URLs only', 'type' => 'bool', 'default' => false],
            ['key' => 'MAX_URL_ITEMS', 'label' => 'URLhaus rows', 'type' => 'number',
             'help' => 'Recent malicious URLs to list (4–12, default 8)'],
            ['key' => 'MAX_BRAND_ITEMS', 'label' => 'Brand hits per row', 'type' => 'number',
             'help' => 'Suspicious CT names shown per watched brand (2–8, default 5)'],
            ['key' => 'CT_LOOKBACK_DAYS', 'label' => 'Brand CT lookback (days)', 'type' => 'number',
             'help' => 'Certificate Transparency scan window per root domain (1–90, default 14)'],
            ['key' => 'BRAND_WATCH', 'label' => 'Brand watch', 'type' => 'rows', 'keyed' => true,
             'help' => 'Root domains to monitor for lookalike certs — keywords optional (defaults to key).',
             'columns' => [
                 ['key' => '_key', 'label' => 'Key'],
                 ['key' => 'label', 'label' => 'Label'],
                 ['key' => 'root_domain', 'label' => 'Root domain', 'wide' => true,
                  'help' => 'e.g. gvsu.edu or vdrs.fyi'],
                 ['key' => 'keywords', 'label' => 'Keywords', 'wide' => true,
                  'help' => 'Comma-separated tokens to match in suspicious hostnames'],
                 ['key' => 'off', 'label' => 'Off', 'type' => 'bool'],
             ]],
            ['key' => 'URLHAUS_CACHE_TTL', 'label' => 'URLhaus cache (seconds)', 'type' => 'number',
             'help' => 'Poll interval — abuse.ch asks for ≥5 min between requests (default 900)'],
            ['key' => 'CT_CACHE_TTL', 'label' => 'CT cache (seconds)', 'type' => 'number',
             'help' => 'crt.sh is slow — default 86400 (24 h) per root domain'],
            ['key' => 'USER_AGENT', 'label' => 'User-Agent', 'type' => 'text',
             'help' => 'Sent on URLhaus and crt.sh requests'],
            ['key' => 'RELOAD_SEC', 'label' => 'Page reload (seconds)', 'type' => 'number',
             'help' => 'Direct view only — rotation iframe reloads with the shell'],
            $tz,
        ]],
        'internet' => ['title' => 'Internet Infrastructure', 'file' => 'internet.php', 'fields' => [
            ['key' => 'TITLE', 'label' => 'Board title', 'type' => 'text'],
            ['key' => 'SUBTITLE', 'label' => 'Subtitle', 'type' => 'text'],
            ['key' => 'ENABLE_BGP', 'label' => 'Show BGP / ASN outages', 'type' => 'bool', 'default' => true],
            ['key' => 'ENABLE_DNS_ROOTS', 'label' => 'Show DNS root probes', 'type' => 'bool', 'default' => true],
            ['key' => 'US_ONLY', 'label' => 'US scope (IODA)', 'type' => 'bool', 'default' => false,
             'help' => 'Limit IODA routing events to those related to the United States'],
            ['key' => 'LOOKBACK_DAYS', 'label' => 'IODA lookback (days)', 'type' => 'number',
             'help' => 'BGP/ASN events from the last N days (1–30, default 7)'],
            ['key' => 'MAX_BGP_ITEMS', 'label' => 'Routing event count', 'type' => 'number',
             'help' => 'Featured + list items (4–12, default 8)'],
            ['key' => 'USER_AGENT', 'label' => 'User-Agent', 'type' => 'text',
             'help' => 'Sent on IODA API requests'],
            ['key' => 'DNS_CACHE_TTL', 'label' => 'DNS probe cache (seconds)', 'type' => 'number',
             'help' => 'How long to cache root-server probes (default 180s)'],
            ['key' => 'RELOAD_SEC', 'label' => 'Page reload (seconds)', 'type' => 'number',
             'help' => 'Direct view only — rotation iframe reloads with the shell'],
            $tz, $ttl('IODA outage data — default 300s'),
        ]],
        'attacks' => ['title' => 'Internet Attacks', 'file' => 'attacks.php', 'fields' => [
            ['key' => 'TITLE', 'label' => 'Board title', 'type' => 'text'],
            ['key' => 'SUBTITLE', 'label' => 'Subtitle', 'type' => 'text'],
            ['key' => 'ENABLE_DSHIELD', 'label' => 'Show DShield (SANS ISC)', 'type' => 'bool', 'default' => true],
            ['key' => 'HIGHLIGHT_US', 'label' => 'Highlight United States', 'type' => 'bool', 'default' => true,
             'help' => 'Pin US to the top of country lists and accent US rows'],
            ['key' => 'MAX_COUNTRIES', 'label' => 'Country count', 'type' => 'number',
             'help' => 'Featured + list items (4–15, default 10)'],
            ['key' => 'MAX_PORTS', 'label' => 'Port count', 'type' => 'number',
             'help' => 'Top targeted ports (4–12, default 8)'],
            ['key' => 'MAX_IPS', 'label' => 'IP count', 'type' => 'number',
             'help' => 'Top attacking IPs (4–12, default 8)'],
            ['key' => 'USER_AGENT', 'label' => 'User-Agent', 'type' => 'text',
             'help' => 'Sent on DShield requests'],
            ['key' => 'RELOAD_SEC', 'label' => 'Page reload (seconds)', 'type' => 'number',
             'help' => 'Direct view only — rotation iframe reloads with the shell'],
            $tz, $ttl('DShield feeds — default 300s'),
        ]],
        'radar' => ['title' => 'Cloudflare Radar', 'file' => 'radar.php', 'fields' => [
            ['key' => 'TITLE', 'label' => 'Board title', 'type' => 'text'],
            ['key' => 'SUBTITLE', 'label' => 'Subtitle', 'type' => 'text'],
            ['key' => 'CF_API_TOKEN', 'label' => 'Cloudflare API token', 'type' => 'password',
             'help' => 'Free Cloudflare account — create token with Account → Radar permission at dash.cloudflare.com/profile/api-tokens'],
            ['key' => 'DATE_RANGE', 'label' => 'Time window', 'type' => 'select',
             'options' => ['1d' => 'Last 24 hours', '7d' => 'Last 7 days', '14d' => 'Last 14 days', '28d' => 'Last 28 days'],
             'default' => '1d'],
            ['key' => 'ENABLE_L3_TARGETS', 'label' => 'Show L3 DDoS targets', 'type' => 'bool', 'default' => true],
            ['key' => 'ENABLE_L3_ORIGINS', 'label' => 'Show L3 attack origins', 'type' => 'bool', 'default' => true],
            ['key' => 'ENABLE_L7_TARGETS', 'label' => 'Show L7 attack targets', 'type' => 'bool', 'default' => true],
            ['key' => 'HIGHLIGHT_US', 'label' => 'Highlight United States', 'type' => 'bool', 'default' => true,
             'help' => 'Pin US to the top of country lists and accent US rows'],
            ['key' => 'MAX_COUNTRIES', 'label' => 'Country count per panel', 'type' => 'number',
             'help' => 'Items per L3/L7 list (4–15, default 10)'],
            ['key' => 'USER_AGENT', 'label' => 'User-Agent', 'type' => 'text',
             'help' => 'Sent on Cloudflare Radar requests'],
            ['key' => 'RELOAD_SEC', 'label' => 'Page reload (seconds)', 'type' => 'number',
             'help' => 'Direct view only — rotation iframe reloads with the shell'],
            $tz, $ttl('Cloudflare Radar — default 300s'),
        ]],
        'attackmap' => ['title' => 'Attack Map', 'file' => 'attackmap.php', 'fields' => [
            ['key' => 'TITLE', 'label' => 'Board title', 'type' => 'text'],
            ['key' => 'SUBTITLE', 'label' => 'Subtitle', 'type' => 'text'],
            ['key' => 'CF_API_TOKEN', 'label' => 'Cloudflare API token', 'type' => 'password',
             'help' => 'Optional if already set on Cloudflare Radar — Account → Radar permission'],
            ['key' => 'DATE_RANGE', 'label' => 'Time window', 'type' => 'select',
             'options' => ['' => 'Same as Radar board', '1d' => 'Last 24 hours', '7d' => 'Last 7 days', '14d' => 'Last 14 days', '28d' => 'Last 28 days'],
             'default' => ''],
            ['key' => 'MAX_FLOWS', 'label' => 'Arc count', 'type' => 'number',
             'help' => 'L7 origin→target pairs to draw (6–30, default 18)'],
            ['key' => 'ANIM_SEC', 'label' => 'Arc travel (seconds)', 'type' => 'number',
             'help' => 'How long each pew takes to cross the map (2–12, default 4.5)'],
            ['key' => 'USER_AGENT', 'label' => 'User-Agent', 'type' => 'text',
             'help' => 'Sent on Cloudflare Radar requests — leave blank to use Radar board setting'],
            ['key' => 'RELOAD_SEC', 'label' => 'Page reload (seconds)', 'type' => 'number',
             'help' => 'Refresh data and replay arcs — default 300; 0 disables', 'default' => 300],
            $tz, $ttl('Attack map flows — default 300s'),
        ]],
        'dshieldmap' => ['title' => 'DShield Heatmap', 'file' => 'dshieldmap.php', 'fields' => [
            ['key' => 'TITLE', 'label' => 'Board title', 'type' => 'text'],
            ['key' => 'SUBTITLE', 'label' => 'Subtitle', 'type' => 'text'],
            ['key' => 'ENABLE_DSHIELD', 'label' => 'Show DShield heatmap', 'type' => 'bool', 'default' => true,
             'help' => 'Leave enabled — uses the same isc.sans.edu feed as Internet Attacks (no API key)'],
            ['key' => 'MIN_TARGETS', 'label' => 'Minimum targets', 'type' => 'number',
             'help' => 'Hide countries below this target count on the map (0–5000, default 100)'],
            ['key' => 'MAX_SIDEBAR', 'label' => 'Sidebar country count', 'type' => 'number',
             'help' => 'Top countries in the right panel (4–12, default 8)'],
            ['key' => 'RELOAD_SEC', 'label' => 'Page reload (seconds)', 'type' => 'number',
             'help' => 'Refresh heatmap data — default 300; 0 disables', 'default' => 300],
            $tz, $ttl('Shares DShield cache with Internet Attacks — default 300s'),
        ]],
        'dshieldsrc' => ['title' => 'Attack Origins', 'file' => 'dshieldsrc.php', 'fields' => [
            ['key' => 'TITLE', 'label' => 'Board title', 'type' => 'text'],
            ['key' => 'SUBTITLE', 'label' => 'Subtitle', 'type' => 'text'],
            ['key' => 'ENABLE_DSHIELD', 'label' => 'Show DShield sources map', 'type' => 'bool', 'default' => true],
            ['key' => 'MIN_SOURCES', 'label' => 'Minimum sources', 'type' => 'number',
             'help' => 'Hide countries below this source count (0–5000, default 100)'],
            ['key' => 'MAX_SIDEBAR', 'label' => 'Sidebar country count', 'type' => 'number',
             'help' => 'Top source countries in the right panel (4–12, default 8)'],
            ['key' => 'RELOAD_SEC', 'label' => 'Page reload (seconds)', 'type' => 'number',
             'help' => 'Refresh map — default 300; 0 disables', 'default' => 300],
            $tz, $ttl('Shares DShield cache with Internet Attacks — default 300s'),
        ]],
        'attackports' => ['title' => 'Top Attack Ports', 'file' => 'attackports.php', 'fields' => [
            ['key' => 'TITLE', 'label' => 'Board title', 'type' => 'text'],
            ['key' => 'SUBTITLE', 'label' => 'Subtitle', 'type' => 'text'],
            ['key' => 'ENABLE_DSHIELD', 'label' => 'Show DShield ports', 'type' => 'bool', 'default' => true],
            ['key' => 'MAX_PORTS', 'label' => 'Port count in treemap', 'type' => 'number',
             'help' => 'Top targeted ports to draw (6–24, default 16)'],
            ['key' => 'RELOAD_SEC', 'label' => 'Page reload (seconds)', 'type' => 'number',
             'help' => 'Refresh treemap — default 300; 0 disables', 'default' => 300],
            $tz, $ttl('Shares DShield topports cache — default 300s'),
        ]],
        'iodamap' => ['title' => 'Outage Map', 'file' => 'iodamap.php', 'fields' => [
            ['key' => 'TITLE', 'label' => 'Board title', 'type' => 'text'],
            ['key' => 'SUBTITLE', 'label' => 'Subtitle', 'type' => 'text'],
            ['key' => 'ENABLE_IODA', 'label' => 'Show IODA outage map', 'type' => 'bool', 'default' => true],
            ['key' => 'LOOKBACK_DAYS', 'label' => 'Lookback (days)', 'type' => 'number',
             'help' => '0 = same as Internet Infrastructure board (default 7)'],
            ['key' => 'MIN_SCORE', 'label' => 'Minimum outage score', 'type' => 'number',
             'help' => 'Filter weak signals (default 3000)'],
            ['key' => 'MAX_SIDEBAR', 'label' => 'Sidebar country count', 'type' => 'number',
             'help' => 'Top outage countries (4–12, default 8)'],
            ['key' => 'RELOAD_SEC', 'label' => 'Page reload (seconds)', 'type' => 'number',
             'help' => 'Refresh map — default 300; 0 disables', 'default' => 300],
            $tz, $ttl('IODA outage data — default 300s'),
        ]],
        'l3map' => ['title' => 'L3 Attack Map', 'file' => 'l3map.php', 'fields' => [
            ['key' => 'TITLE', 'label' => 'Board title', 'type' => 'text'],
            ['key' => 'SUBTITLE', 'label' => 'Subtitle', 'type' => 'text'],
            ['key' => 'CF_API_TOKEN', 'label' => 'Cloudflare API token', 'type' => 'password',
             'help' => 'Optional if already set on Cloudflare Radar or Attack Map'],
            ['key' => 'DATE_RANGE', 'label' => 'Time window', 'type' => 'select',
             'options' => ['' => 'Same as Radar board', '1d' => 'Last 24 hours', '7d' => 'Last 7 days', '14d' => 'Last 14 days', '28d' => 'Last 28 days'],
             'default' => ''],
            ['key' => 'MAX_FLOWS', 'label' => 'Arc count', 'type' => 'number',
             'help' => 'L3 origin→target pairs to draw (6–30, default 18)'],
            ['key' => 'ANIM_SEC', 'label' => 'Arc travel (seconds)', 'type' => 'number',
             'help' => 'How long each arc takes to cross the map (2–12, default 5)'],
            ['key' => 'USER_AGENT', 'label' => 'User-Agent', 'type' => 'text',
             'help' => 'Sent on Cloudflare Radar requests'],
            ['key' => 'RELOAD_SEC', 'label' => 'Page reload (seconds)', 'type' => 'number',
             'help' => 'Refresh data and replay arcs — default 300; 0 disables', 'default' => 300],
            $tz, $ttl('L3 attack map flows — default 300s'),
        ]],
        'homelab' => ['title' => 'Homelab Ops', 'file' => 'homelab.php', 'fields' => [
            ['key' => 'PVE_HOST', 'label' => 'Proxmox host', 'type' => 'text', 'help' => 'https://host:8006'],
            ['key' => 'PVE_TOKEN_ID', 'label' => 'Proxmox token ID', 'type' => 'text', 'help' => 'user@realm!tokenid'],
            ['key' => 'PVE_TOKEN_SECRET', 'label' => 'Proxmox token secret', 'type' => 'password'],
            ['key' => 'PVE_VERIFY_TLS', 'label' => 'Verify Proxmox TLS', 'type' => 'bool', 'default' => false, 'help' => 'Off for self-signed certs'],
            ['key' => 'ADGUARD_URL', 'label' => 'AdGuard Home URL', 'type' => 'text'],
            ['key' => 'ADGUARD_USER', 'label' => 'AdGuard user', 'type' => 'text'],
            ['key' => 'ADGUARD_PASS', 'label' => 'AdGuard password', 'type' => 'password'],
            ['key' => 'SERVICES', 'label' => 'Service checks', 'type' => 'rows', 'keyed' => true, 'scalar' => true,
             'columns' => [
                 ['key' => '_key', 'label' => 'Name'],
                 ['key' => '_value', 'label' => 'URL'],
             ],
             'help' => 'HTTP(S) endpoints to ping for up/down and response time. Leave empty for none. '
                     . 'Do not use SignalTrace honeypot/token URLs — checks register as hits. '
                     . 'User-Agent is HomeSignage/ServiceCheck/1.0 (add a skip pattern in SignalTrace if needed).'],
            ['key' => 'LATENCY_TARGET', 'label' => 'WAN latency target', 'type' => 'text'],
            $tz, $ttl(),
        ]],
        'unifi' => ['title' => 'UniFi Network', 'file' => 'unifi.php', 'fields' => [
            ['key' => 'UNIFI_URL', 'label' => 'Controller URL', 'type' => 'text',
             'help' => 'Dream Machine / UDM: https://192.168.x.x (gateway IP, port 443). No /network path.'],
            ['key' => 'UNIFI_API_KEY', 'label' => 'Integration API key (optional)', 'type' => 'password',
             'help' => 'Only on newer Network (9.3+) under Settings → Integrations. Leave blank on most UDMs — use local admin below.'],
            ['key' => 'UNIFI_SITE', 'label' => 'Site', 'type' => 'text', 'default' => 'default',
             'help' => 'Usually default on a single-site Dream Machine'],
            ['key' => 'UNIFI_USERNAME', 'label' => 'Local admin user', 'type' => 'text',
             'help' => 'Dream Machine: create under Settings → Admins — must be a local account with local access (not ui.com-only).'],
            ['key' => 'UNIFI_PASSWORD', 'label' => 'Local admin password', 'type' => 'password'],
            ['key' => 'UNIFI_VERIFY_TLS', 'label' => 'Verify TLS', 'type' => 'bool', 'default' => false,
             'help' => 'Off for self-signed LAN certificates'],
            ['key' => 'BOARD_TITLE', 'label' => 'Board title', 'type' => 'text', 'default' => 'UniFi'],
            ['key' => 'BOARD_SUB', 'label' => 'Board subtitle', 'type' => 'text', 'default' => 'Network'],
            ['key' => 'MAX_DEVICES', 'label' => 'Max devices shown', 'type' => 'number', 'default' => 24],
            ['key' => 'TOP_TALKERS', 'label' => 'Top talkers shown', 'type' => 'number', 'default' => 4],
            $tz, $ttl('Device and client queries'),
        ]],
        'kuma' => ['title' => 'Uptime Kuma', 'file' => 'kuma.php', 'fields' => [
            ['key' => 'KUMA_URL', 'label' => 'Uptime Kuma URL', 'type' => 'text',
             'help' => 'Base URL, e.g. http://192.168.x.x:3001 — no trailing path. LAN hosts need Security → Allow private URL fetches.'],
            ['key' => 'KUMA_API_KEY', 'label' => 'API key (optional)', 'type' => 'password',
             'help' => 'Settings → API Keys in Uptime Kuma (Bearer token). Lists all monitors; per-page status slugs enrich heartbeat data.'],
            ['key' => 'KUMA_VERIFY_TLS', 'label' => 'Verify TLS', 'type' => 'bool', 'default' => false],
            ['key' => 'BOARD_TITLE', 'label' => 'Default page title', 'type' => 'text', 'default' => 'Uptime Kuma',
             'help' => 'Used for the main page when no per-page title is set'],
            ['key' => 'BOARD_SUB', 'label' => 'Default page subtitle', 'type' => 'text', 'default' => 'Monitoring'],
            ['key' => 'MAX_MONITORS', 'label' => 'Default max monitors', 'type' => 'number', 'default' => 24,
             'help' => 'Per-page override available on each tab below'],
            $tz, $ttl('Monitor status queries'),
        ]],
        'tailscale' => ['title' => 'Tailscale', 'file' => 'tailscale.php', 'fields' => [
            ['key' => 'TAILNET', 'label' => 'Tailnet name', 'type' => 'text',
             'help' => 'Your tailnet name from the Tailscale admin console URL, e.g. example.com or example.ts.net'],
            ['key' => 'TAILSCALE_API_KEY', 'label' => 'API key', 'type' => 'password',
             'help' => 'Keys → Generate API key in Tailscale admin (read devices).'],
            ['key' => 'BOARD_TITLE', 'label' => 'Board title', 'type' => 'text', 'default' => 'Tailscale'],
            ['key' => 'BOARD_SUB', 'label' => 'Board subtitle', 'type' => 'text', 'default' => 'Mesh network'],
            ['key' => 'MAX_DEVICES', 'label' => 'Max devices shown', 'type' => 'number', 'default' => 32],
            $tz, $ttl('Device list queries'),
        ]],
        'ntfy' => ['title' => 'ntfy Alerts', 'file' => 'ntfy.php', 'fields' => [
            ['key' => 'NTFY_WEBHOOK_TOKEN', 'label' => 'Webhook token', 'type' => 'password',
             'help' => 'Shared secret for ntfy_webhook.php — send as X-Signage-Token header or ?token='],
            ['key' => 'NTFY_SERVER', 'label' => 'ntfy server', 'type' => 'text', 'default' => 'https://ntfy.sh',
             'help' => 'Base URL for poll mode — self-hosted or ntfy.sh'],
            ['key' => 'NTFY_POLL_TOPIC', 'label' => 'Poll topic', 'type' => 'text',
             'help' => 'Optional — poll /topic/json every NTFY_POLL_SEC (works without webhook)'],
            ['key' => 'NTFY_POLL_SEC', 'label' => 'Poll interval (sec)', 'type' => 'number', 'default' => 30],
            ['key' => 'NTFY_MAX_MESSAGES', 'label' => 'Cache size', 'type' => 'number', 'default' => 40],
            ['key' => 'BOARD_TITLE', 'label' => 'Board title', 'type' => 'text', 'default' => 'Recent Alerts'],
            ['key' => 'BOARD_SUB', 'label' => 'Board subtitle', 'type' => 'text', 'default' => 'ntfy'],
            ['key' => 'MAX_SHOWN', 'label' => 'Alerts on wall', 'type' => 'number', 'default' => 10],
            $tz,
        ]],
        'rotator' => ['title' => 'Photo Rotator', 'file' => 'rotator.php', 'fields' => [
            ['key' => 'PHOTO_DIR', 'label' => 'Photo directory', 'type' => 'text',
             'help' => 'Default ./photos — must be writable by the web server. Upload in admin or copy files manually.'],
            ['key' => 'BRAND', 'label' => 'Brand wordmark', 'type' => 'text'],
            ['key' => 'DEFAULT_DWELL', 'label' => 'Default seconds per photo', 'type' => 'number'],
            ['key' => 'INTERVAL_SEC', 'label' => 'Seconds per photo (slideshow)', 'type' => 'number',
             'help' => 'Timing inside combined rotator.php and group pages'],
            ['key' => 'DEPLOY_MODE', 'label' => 'Rotation deploy mode', 'type' => 'select',
             'options' => ['individual', 'groups', 'legacy'], 'default' => 'individual',
             'help' => 'individual = one playlist entry per photo; groups = bundle by group name; legacy = single rotator.php'],
            ['key' => 'SHUFFLE', 'label' => 'Shuffle order', 'type' => 'bool', 'default' => true],
            ['key' => 'SHOW_EXIF', 'label' => 'Show EXIF caption', 'type' => 'bool', 'default' => true],
            ['key' => 'SHOW_CLOCK', 'label' => 'Show clock overlay', 'type' => 'bool', 'default' => true],
            ['key' => 'PHOTOS', 'label' => 'Photo deck', 'type' => 'rows',
             'columns' => [
                 ['key' => 'file', 'label' => 'File', 'wide' => true, 'placeholder' => 'name.jpg'],
                 ['key' => 'caption', 'label' => 'Label', 'wide' => true],
                 ['key' => 'dwell', 'label' => 'Dwell (s)', 'cast' => 'int'],
                 ['key' => 'group', 'label' => 'Group', 'placeholder' => 'travel'],
             ]],
            $tz,
        ]],
        'slides' => ['title' => 'Custom Slides', 'file' => 'slides.php', 'fields' => [
            ['key' => 'SLIDE_DIR', 'label' => 'Slide directory', 'type' => 'text',
             'help' => 'Default ./slides — must be writable by the web server'],
            ['key' => 'DEFAULT_DWELL', 'label' => 'Default seconds per slide', 'type' => 'number'],
            ['key' => 'SHUFFLE', 'label' => 'Shuffle active slides', 'type' => 'bool', 'default' => false],
            ['key' => 'FIT', 'label' => 'Image fit', 'type' => 'select', 'options' => ['contain', 'cover']],
            ['key' => 'SHOW_CLOCK', 'label' => 'Show clock overlay', 'type' => 'bool', 'default' => true,
             'help' => 'Fixed top-right on each slide; uses the timezone below'],
            ['key' => 'SLIDES', 'label' => 'Slide deck', 'type' => 'rows',
             'columns' => [
                 ['key' => 'file', 'label' => 'File', 'wide' => true, 'placeholder' => 'name.jpg'],
                 ['key' => 'caption', 'label' => 'Caption', 'wide' => true],
                 ['key' => 'dwell', 'label' => 'Dwell (s)', 'cast' => 'int'],
                 ['key' => 'schedule', 'label' => 'Schedule', 'type' => 'select',
                  'options' => ['always', 'once', 'range', 'yearly', 'yearly_range', 'monthly', 'weekly']],
                 ['key' => 'date_start', 'label' => 'From', 'placeholder' => 'YYYY-MM-DD or once'],
                 ['key' => 'date_end', 'label' => 'To', 'placeholder' => 'YYYY-MM-DD'],
                 ['key' => 'month_day', 'label' => 'MM-DD', 'placeholder' => 'MM-DD start'],
                 ['key' => 'month_day_end', 'label' => 'MM-DD end', 'placeholder' => 'yearly range'],
                 ['key' => 'day_of_month', 'label' => 'Day', 'placeholder' => '1-31', 'cast' => 'int'],
                 ['key' => 'weekday', 'label' => 'Weekday', 'type' => 'select',
                  'options' => ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']],
                 ['key' => 'weekdays', 'label' => 'Days', 'placeholder' => 'Mon,Wed,Fri'],
                 ['key' => 'hour_from', 'label' => 'Hr from', 'placeholder' => '0-23', 'cast' => 'int'],
                 ['key' => 'hour_to', 'label' => 'Hr to', 'placeholder' => '0-23', 'cast' => 'int'],
                 ['key' => 'priority', 'label' => 'Priority', 'type' => 'check'],
                 ['key' => 'off', 'label' => 'Off', 'type' => 'check'],
             ],
             'help' => 'Use cards below — schedule fields appear based on type.'],
            $tz,
        ]],
        'calendar' => ['title' => 'Calendar', 'file' => 'calendar.php', 'fields' => [
            ['key' => 'ICS_FEEDS', 'label' => 'Calendar feeds', 'type' => 'rows',
             'columns' => [
                 ['key' => 'key', 'label' => 'Key', 'placeholder' => 'Dad'],
                 ['key' => 'color', 'label' => 'Color', 'type' => 'palette'],
                 ['key' => 'source', 'label' => 'Source', 'type' => 'select',
                  'options' => ['ical', 'webdav']],
                 ['key' => 'url', 'label' => 'URL', 'wide' => true],
                 ['key' => 'user', 'label' => 'User', 'placeholder' => 'email for CalDAV'],
                 ['key' => 'password', 'label' => 'Password', 'type' => 'password'],
             ],
             'help' => 'Key is the legend label on the wall (e.g. Dad, Mom). Pick a theme color per feed. '
                     . 'ical: secret iCal URL. webdav: CalDAV (Fastmail, Nextcloud, …) with app password. '
                     . 'LAN/private hosts need Security → Allow private URL fetches.'],
            ['key' => 'TRASH_WEEKDAY', 'label' => 'Trash day', 'type' => 'select',
             'options' => ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],
             'help' => 'Leave as (default) to hide — e.g. apartment living'],
            ['key' => 'RECYCLE_ANCHOR', 'label' => 'Recycle anchor date', 'type' => 'text',
             'help' => 'Only used when trash day is set. Any past pickup date (YYYY-MM-DD); empty disables biweekly recycle'],
            ['key' => 'COUNTDOWNS', 'label' => 'Countdowns', 'type' => 'rows', 'keyed' => true, 'scalar' => true,
             'columns' => [
                 ['key' => '_key', 'label' => 'Label'],
                 ['key' => '_value', 'label' => 'Date (YYYY-MM-DD)'],
             ]],
            $tz, $ttl(),
        ]],
        'glance' => ['title' => 'Today at a Glance', 'file' => 'glance.php', 'fields' => [
            ['key' => 'TITLE', 'label' => 'Board title', 'type' => 'text', 'default' => 'Today at a glance'],
            ['key' => 'SUBTITLE', 'label' => 'Subtitle', 'type' => 'text'],
            ['key' => 'MAX_TODAY', 'label' => 'Today events shown', 'type' => 'number',
             'help' => 'How many of today\'s events to list (3–16, default 8)'],
            ['key' => 'SHOW_TOMORROW', 'label' => 'Show tomorrow preview', 'type' => 'bool', 'default' => true],
            ['key' => 'SHOW_WEATHER', 'label' => 'Show weather summary', 'type' => 'bool', 'default' => true,
             'help' => 'Current conditions from the Weather board OWM key and this display\'s rotation location'],
            ['key' => 'SHOW_HEADLINES_1', 'label' => 'Show left headline column (site default)', 'type' => 'bool', 'default' => true],
            ['key' => 'HEADLINES_1_TITLE', 'label' => 'Left column title (site default)', 'type' => 'text', 'default' => 'GVNext'],
            ['key' => 'HEADLINES_1_PAGE_URL', 'label' => 'Left column page URL (site default)', 'type' => 'text', 'wide' => true,
             'default' => 'https://www.gvsu.edu/gvnext/',
             'help' => 'Override per display under Rotation → Kiosk settings. GVNext homepage by default.'],
            ['key' => 'HEADLINES_1_RSS', 'label' => 'Left column RSS fallback (site default)', 'type' => 'text',
             'help' => 'Feed key from RSS Stories if page scrape fails. Override per display in Rotation kiosk settings.'],
            ['key' => 'HEADLINES_1_MAX', 'label' => 'Left headlines shown', 'type' => 'number',
             'help' => 'How many titles to list (3–8, default 5)'],
            ['key' => 'SHOW_HEADLINES_2', 'label' => 'Show right headline column (site default)', 'type' => 'bool', 'default' => true],
            ['key' => 'HEADLINES_2_TITLE', 'label' => 'Right column title (site default)', 'type' => 'text', 'default' => 'News'],
            ['key' => 'HEADLINES_2_RSS', 'label' => 'Right column RSS feed key (site default)', 'type' => 'text',
             'help' => 'Feed key from RSS Stories. Override per display in Rotation kiosk settings.'],
            ['key' => 'HEADLINES_2_MAX', 'label' => 'Right headlines shown', 'type' => 'number',
             'help' => 'How many titles to list (3–8, default 5)'],
            ['key' => 'HEADLINES_CACHE_TTL', 'label' => 'Headlines cache (seconds)', 'type' => 'number',
             'help' => 'Defaults to RSS Stories cache TTL when unset'],
            ['key' => 'RELOAD_SEC', 'label' => 'Page reload (seconds)', 'type' => 'number',
             'help' => 'Direct view only — rotation iframe reloads with the shell'],
            $tz,
            ['key' => 'CACHE_TTL', 'label' => 'Calendar fetch cache (seconds)', 'type' => 'number',
             'help' => 'Uses Calendar board feeds (calendar.ICS_FEEDS) — same cache TTL as Calendar when unset'],
        ]],
        'meals' => ['title' => 'Meal Calendar', 'file' => 'meals.php', 'fields' => [
            ['key' => 'TITLE', 'label' => 'Board title', 'type' => 'text', 'default' => 'Meal calendar'],
            ['key' => 'SUBTITLE', 'label' => 'Subtitle', 'type' => 'text', 'default' => 'This week'],
            ['key' => 'WEEKLY_PLAN', 'label' => 'Weekly plan', 'type' => 'rows',
             'columns' => [
                 ['key' => 'weekday', 'label' => 'Day', 'type' => 'select',
                  'options' => ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']],
                 ['key' => 'dinner', 'label' => 'Dinner', 'wide' => true],
                 ['key' => 'note', 'label' => 'Note', 'wide' => true,
                  'placeholder' => 'Sides, prep, eat-out, etc.'],
                 ['key' => 'lunch', 'label' => 'Lunch', 'wide' => true],
                 ['key' => 'breakfast', 'label' => 'Breakfast', 'wide' => true],
             ],
             'help' => 'Default meals by weekday — one row per day. Dinner is shown on the wall by default.'],
            ['key' => 'DATE_OVERRIDES', 'label' => 'Date overrides', 'type' => 'rows',
             'columns' => [
                 ['key' => 'date', 'label' => 'Date', 'placeholder' => 'YYYY-MM-DD'],
                 ['key' => 'dinner', 'label' => 'Dinner', 'wide' => true],
                 ['key' => 'note', 'label' => 'Note', 'wide' => true],
                 ['key' => 'lunch', 'label' => 'Lunch', 'wide' => true],
                 ['key' => 'breakfast', 'label' => 'Breakfast', 'wide' => true],
             ],
             'help' => 'Replace the weekly plan on specific dates — holidays, leftovers night, dinner out.'],
            ['key' => 'SHOW_LUNCH', 'label' => 'Show lunch on wall', 'type' => 'bool', 'default' => false],
            ['key' => 'SHOW_BREAKFAST', 'label' => 'Show breakfast on wall', 'type' => 'bool', 'default' => false],
            ['key' => 'RELOAD_SEC', 'label' => 'Page reload (seconds)', 'type' => 'number',
             'help' => 'Direct view only — rotation iframe reloads with the shell'],
            $tz,
        ]],
        'rss' => ['title' => 'RSS Stories', 'file' => 'rss.php', 'fields' => [
            ['key' => 'FEEDS', 'label' => 'Feeds', 'type' => 'rows', 'keyed' => true,
             'columns' => [
                 ['key' => '_key', 'label' => 'Key', 'help' => 'used in ?feed='],
                 ['key' => 'name', 'label' => 'Display name'],
                 ['key' => 'url', 'label' => 'Feed URL', 'wide' => true],
                 ['key' => 'stories', 'label' => '# stories', 'cast' => 'int'],
                 ['key' => 'dwell', 'label' => 'Secs/story', 'cast' => 'int'],
                 ['key' => 'fit', 'label' => 'Image fit', 'type' => 'select',
                  'options' => ['', 'auto', 'cover', 'contain'],
                  'help' => 'Blank = site default'],
             ]],
            ['key' => 'DEFAULT_STORIES', 'label' => 'Default stories per cycle', 'type' => 'number'],
            ['key' => 'DEFAULT_DWELL', 'label' => 'Default seconds per story', 'type' => 'number'],
            ['key' => 'SYNOPSIS_CHARS', 'label' => 'Synopsis length (chars)', 'type' => 'number'],
            ['key' => 'FIT', 'label' => 'Image fit', 'type' => 'select',
             'options' => ['auto', 'cover', 'contain'], 'default' => 'auto',
             'help' => 'auto = landscape fills the screen; portrait images show full height on the right with a blurred backdrop. cover = always crop to fill. contain = always show the full image.'],
            $tz, $ttl(),
        ]],
        'video' => ['title' => 'Video Board', 'file' => 'video.php', 'fields' => [
            ['key' => 'VIDEOS', 'label' => 'Videos', 'type' => 'rows', 'keyed' => true,
             'columns' => [['key' => '_key', 'label' => 'Key', 'help' => 'used in ?v='],
                           ['key' => 'title', 'label' => 'Title (blank to hide)'],
                           ['key' => 'youtube', 'label' => 'YouTube URL', 'wide' => true],
                           ['key' => 'file', 'label' => 'or local file']],
             'help' => 'Managed on this page via the drag-and-drop playlist below. Each video needs a unique key. '
                     . 'Use Admin → Rotation to order all boards on the wall, or check “Add playlist to main rotation” when saving.'],
            ['key' => 'VIDEO_DIR', 'label' => 'Video directory', 'type' => 'text'],
            ['key' => 'MUTED', 'label' => 'Mute all videos', 'type' => 'bool', 'default' => true,
             'help' => 'Uncheck to play sound. Kiosks need setup-kiosk.sh (includes autoplay-policy for unmuted video).'],
            ['key' => 'FIT', 'label' => 'Fit', 'type' => 'select', 'options' => ['cover', 'contain']],
            ['key' => 'SHOW_CLOCK', 'label' => 'Show clock', 'type' => 'bool', 'default' => true],
            ['key' => 'MAX_HEIGHT', 'label' => 'Max download height', 'type' => 'number'],
            ['key' => 'YTDLP_COOKIES_FILE', 'label' => 'YouTube cookies file', 'type' => 'text',
             'help' => 'Netscape cookies.txt path (default config/cookies/youtube.txt). Export from a logged-in browser — see README.'],
            ['key' => 'YTDLP_JS_RUNTIME', 'label' => 'JS runtime', 'type' => 'select',
             'options' => ['auto', 'deno', 'node', 'none'], 'default' => 'auto',
             'help' => 'YouTube needs a JS runtime (deno recommended; setup-server.sh installs it)'],
            $tz,
        ]],
        'grafana' => ['title' => 'Grafana', 'file' => 'grafana.php', 'fields' => [
            ['key' => 'DASHBOARDS', 'label' => 'Dashboards', 'type' => 'rows', 'keyed' => true,
             'columns' => [
                 ['key' => '_key', 'label' => 'Key', 'help' => 'used in ?d='],
                 ['key' => 'title', 'label' => 'Title'],
                 ['key' => 'url', 'label' => 'Dashboard URL', 'wide' => true],
                 ['key' => 'refresh', 'label' => 'Refresh', 'placeholder' => '30s'],
                 ['key' => 'params', 'label' => 'Extra params'],
             ]],
            ['key' => 'GRAFANA_THEME', 'label' => 'Theme', 'type' => 'select', 'options' => ['dark', 'light']],
            $tz,
        ]],
        'splunk' => ['title' => 'Splunk Panels', 'file' => 'splunk.php', 'fields' => [
            ['key' => 'SPLUNK_BASE', 'label' => 'Splunk management URL', 'type' => 'text', 'help' => 'Port 8089, not Splunk Web'],
            ['key' => 'SPLUNK_TOKEN', 'label' => 'Auth token', 'type' => 'password'],
            ['key' => 'SPLUNK_VERIFY_TLS', 'label' => 'Verify TLS', 'type' => 'bool', 'default' => false],
            ['key' => 'BOARD_TITLE', 'label' => 'Default page title', 'type' => 'text', 'help' => 'Used for the main page when no per-page title is set'],
            ['key' => 'BOARD_SUB', 'label' => 'Default page subtitle', 'type' => 'text'],
            $tz, $ttl(),
        ]],
        'zabbix' => ['title' => 'Zabbix Monitoring', 'file' => 'zabbix.php', 'fields' => [
            ['key' => 'ZABBIX_URL', 'label' => 'Zabbix URL', 'type' => 'text',
             'help' => 'Base URL, e.g. https://zabbix.example.com — api_jsonrpc.php is appended automatically. On the same LAN/Proxmox host, prefer the VM IP or internal hostname (not a public URL) to avoid hairpin NAT and DNS delays.'],
            ['key' => 'ZABBIX_TOKEN', 'label' => 'API token', 'type' => 'password',
             'help' => 'Users → API tokens in Zabbix (6.4+). Zabbix 7.2+ requires a token — sent as Authorization: Bearer'],
            ['key' => 'ZABBIX_VERIFY_TLS', 'label' => 'Verify TLS', 'type' => 'bool', 'default' => false],
            ['key' => 'BOARD_TITLE', 'label' => 'Default page title', 'type' => 'text', 'help' => 'Used for the main page when no per-page title is set'],
            ['key' => 'BOARD_SUB', 'label' => 'Default page subtitle', 'type' => 'text'],
            $tz, $ttl('How long problem/host queries are cached'),
        ]],
        'splunkdash' => ['title' => 'Splunk Published', 'file' => 'splunkdash.php', 'fields' => [
            ['key' => 'DASHBOARDS', 'label' => 'Published dashboards', 'type' => 'rows', 'keyed' => true,
             'columns' => [
                 ['key' => '_key', 'label' => 'Key', 'help' => 'used in ?d='],
                 ['key' => 'title', 'label' => 'Title'],
                 ['key' => 'url', 'label' => 'Published URL', 'wide' => true],
                 ['key' => 'reload', 'label' => 'Reload (s)', 'cast' => 'int'],
             ]],
            ['key' => 'DEFAULT_RELOAD', 'label' => 'Default iframe reload (s)', 'type' => 'number', 'help' => '0 disables'],
            $tz,
        ]],
        'web' => ['title' => 'Websites', 'file' => 'web.php', 'fields' => [
            ['key' => 'SITES', 'label' => 'Sites', 'type' => 'rows', 'keyed' => true,
             'columns' => [
                 ['key' => '_key', 'label' => 'Key', 'help' => 'used in ?d='],
                 ['key' => 'title', 'label' => 'Title'],
                 ['key' => 'url', 'label' => 'URL', 'wide' => true, 'help' => 'https://… — must allow iframe embed'],
                 ['key' => 'reload', 'label' => 'Reload (s)', 'cast' => 'int', 'help' => '0 = no iframe refresh backstop'],
             ]],
            ['key' => 'DEFAULT_RELOAD', 'label' => 'Default reload (s)', 'type' => 'number', 'help' => '0 disables; used when a site leaves reload blank'],
            ['key' => 'SHOW_CLOCK', 'label' => 'Show clock overlay', 'type' => 'bool', 'default' => true,
             'help' => 'Fixed top-right over the iframe; uses the timezone below'],
            $tz,
        ]],
        'traffic' => ['title' => 'Traffic Map', 'file' => 'traffic.php', 'fields' => [
            ['key' => 'TOMTOM_API_KEY', 'label' => 'TomTom API key', 'type' => 'password',
             'help' => 'Enable Traffic Flow API on the key; no domain whitelist (server-side tiles)'],
            ['key' => 'TOMTOM_API', 'label' => 'Tile API', 'type' => 'select',
             'options' => ['auto', 'legacy', 'orbis'], 'default' => 'auto',
             'help' => 'Auto tries Orbis (new keys) then legacy v4. Use legacy only for older TomTom accounts.'],
            ['key' => 'TITLE', 'label' => 'Board title', 'type' => 'text'],
            ['key' => 'SUBTITLE', 'label' => 'Subtitle', 'type' => 'text'],
            ['key' => 'LAT', 'label' => 'Map center latitude', 'type' => 'number', 'step' => 'any',
             'help' => 'Default frames I-96 with weight toward Grand Rapids'],
            ['key' => 'LON', 'label' => 'Map center longitude', 'type' => 'number', 'step' => 'any',
             'help' => 'More negative = west; default -85.78 centers east of midpoint (GR side)'],
            ['key' => 'ZOOM', 'label' => 'Zoom level', 'type' => 'number', 'help' => '11 = full corridor; 12 = tighter on GR'],
            ['key' => 'FLOW_STYLE', 'label' => 'Flow style', 'type' => 'select',
             'options' => ['relative0-dark', 'relative0', 'relative', 'absolute'],
             'help' => 'relative0-dark matches the dark basemap best'],
            ['key' => 'RELOAD_SEC', 'label' => 'Refresh interval (seconds)', 'type' => 'number'],
            $tz,
        ]],
        'ticker' => ['title' => 'Alert Ticker', 'file' => 'ticker.php', 'fields' => [
            ['key' => 'TICKER_ENABLED', 'label' => 'Enable weather alert ticker', 'type' => 'bool', 'default' => true,
             'help' => 'Master switch — off hides the ticker everywhere. Per-display on/off is under Rotation → Displays. '
                     . 'Alert location uses the Weather board lat/lon (or each display\'s kiosk location override).'],
            ['key' => 'TICKER_UA', 'label' => 'NWS User-Agent', 'type' => 'text'],
            ['key' => 'TICKER_TTL', 'label' => 'NWS poll interval (s)', 'type' => 'number'],
            ['key' => 'TICKER_MODE', 'label' => 'Mode', 'type' => 'select', 'options' => ['scroll', 'static']],
            ['key' => 'TICKER_MIN_SEVERITY', 'label' => 'Minimum severity', 'type' => 'select',
             'options' => ['Minor', 'Moderate', 'Severe']],
            ['key' => 'TICKER_DEMO', 'label' => 'Demo mode (sample alerts)', 'type' => 'bool', 'default' => false,
             'help' => 'Preview the ticker layout — turn off for production'],
        ]],
    ];
}
