#!/usr/bin/env bash
# Ignore phantom pointer-capable inputs (Pi HDMI, CEC) so cage stops drawing a cursor.
set -euo pipefail

RULES=/etc/udev/rules.d/99-signage-phantom-pointer.rules
declare -A SEEN=()

remember_name() {
  local name="$1"
  [[ -n "$name" ]] || return 0
  SEEN["$name"]=1
}

should_ignore_name() {
  local name="$1"
  local lower
  lower="$(printf '%s' "$name" | tr '[:upper:]' '[:lower:]')"
  case "$lower" in
    *vc4-hdmi*|*hdmi*cec*|*cec*hdmi*) return 0 ;;
  esac
  return 1
}

collect_from_proc() {
  local name=""
  while IFS= read -r line; do
    if [[ "$line" =~ ^N:\ Name=\"(.+)\"$ ]]; then
      name="${BASH_REMATCH[1]}"
      if should_ignore_name "$name"; then
        remember_name "$name"
      fi
    fi
  done < /proc/bus/input/devices
}

collect_from_libinput() {
  command -v libinput >/dev/null 2>&1 || return 0
  local dev="" caps=""
  while IFS= read -r line; do
    if [[ "$line" =~ ^Device:[[:space:]]*(.+)$ ]]; then
      dev="${BASH_REMATCH[1]}"
      dev="${dev#"${dev%%[![:space:]]*}"}"
      caps=""
    elif [[ "$line" =~ ^Capabilities:[[:space:]]*(.+)$ ]]; then
      caps="${BASH_REMATCH[1]}"
      if [[ "$caps" == *pointer* ]] && should_ignore_name "$dev"; then
        remember_name "$dev"
      fi
    elif [[ -z "$line" ]]; then
      dev=""
      caps=""
    fi
  done < <(libinput list-devices 2>/dev/null || true)
}

apt-get install -y -q libinput-tools 2>/dev/null || true

collect_from_proc
collect_from_libinput

if ((${#SEEN[@]} == 0)); then
  remember_name "vc4-hdmi-0"
  remember_name "vc4-hdmi-1"
fi

{
  echo '# Signage kiosk — ignore phantom pointer devices (Pi HDMI / CEC).'
  echo '# Generated by scripts/signage-apply-phantom-pointer-rules.sh'
  for name in "${!SEEN[@]}"; do
    printf 'ACTION!="remove", SUBSYSTEM=="input", ATTRS{name}=="%s", ENV{LIBINPUT_IGNORE_DEVICE}="1"\n' "$name"
  done | sort -u
} > "$RULES"

chmod 644 "$RULES"
udevadm control --reload-rules 2>/dev/null || true
udevadm trigger --subsystem-match=input --action=change 2>/dev/null || true

echo "Wrote $RULES:"
grep -v '^#' "$RULES" | grep -v '^$' || true
